### ISSUE TITLE
homepage is exposing feed.xml which does not exist

### ISSUE THREAD

**Issue by ssbarnea** [willthames/willthames.github.io#5]
Your homepage is exposing feed.xml which does not exist. 

In addition, I discovered that atom.xml exists but is invalid, http://willthames.github.io/atom.xml

```
This page contains the following errors:

error on line 1 at column 1: Document is empty
Below is a rendering of the page up to the first error.
```

This means that we cannot subscribe to your blog.

**Comment by willthames** [comment]
I only spotted this tonight, I'm sorry. This is now fixed to be /feed.xml again, thanks for the feedback
